title: Programming Basics
description: Get started for free now!
baseUrl: 'Course-Portfolio'

sass:
  style: compact
  sass_dir: _sass

exclude:
- Gemfile
- Gemfile.lock
- .gitignore
- scss

collections:
  - home_page_items
  - team_members